NER_SCHEMA = ['motorcycle', 'enabling technology', 'disease', 'truck', 'Dish', 'DNA',
              'brand of vehicle', 'instrument', 'song', 'vehicle', 'time', 'review', 'percent',
              'roadster', 'MPV', 'trailer', 'SUV', 'process parameter',
              'national religious political', 'animal', 'food', 'Price', 'geographical phenomenon',
              'quantity', 'river', 'weapon', 'manufacturing standard', 'date', 'cell line',
              'sports car', 'RNA', 'location', 'engineering feature', 'GENE',
              'process characterization', 'exact location', 'mythical figure', 'vehicle range',
              'vehicle model', 'cardinal', 'language', 'geographical social political', 'protein',
              'character', 'cell type', 'Location', 'estate car', 'hatchback', 'average ratings',
              'bus', 'money', 'rating', 'genre', 'work of art', 'media', 'year', 'road', 'director',
              'vintage car', 'Anatomy', 'mechanical property', 'person', 'actor',
              'astronomical object', 'material', 'facility', 'group', 'Rating', 'law', 'corporation',
              'event', 'vehicle type', 'product', 'manufacturing process', 'Cuisine', 'else',
              'machine or equipment', 'creative work', 'biology', 'biomedical', 'sedan',
              'position of vehicle', 'Hours', 'plant', 'title', 'organization',
              'concept or principle', 'plot', 'Disease', 'area', 'Restaurant Name', 'Amenity',
              'coupe', 'orientation of vehicle', 'color of vehicle', 'Chemical', 'van',
              'vehicle velocity', 'ordinal', 'application']

RE_SCHEMA = ['adverse effect', 'Organization based in', 'Located in', 'Live in', 'Work for',
             'Kill', 'place of death', 'place of birth', 'education degree',
             'education institution', 'cities of residence', 'top members employees', 'members',
             'alternate names', 'origin', 'state or provinces of residence', 'title of person',
             'spouse', 'city of headquarters', 'founded by',
             'state or province of headquarters', 'employee of', 'countries of residence',
             'country of birth', 'founded', 'subsidiaries', 'country of headquarters',
             'ethnicity', 'place lived', 'geographic distribution', 'company industry',
             'country of administrative divisions', 'administrative division of country',
             'location contains', 'person of company', 'profession', 'ethnicity of people',
             'company shareholder among major shareholders', 'sports team of location',
             'religion', 'neighborhood of', 'company major shareholders', 'place of death',
             'nationality', 'children', 'company founders', 'company founded place',
             'country of capital', 'company advisors', 'sports team location of teams',
             'place of birth', 'nationality', 'country capital', 'place of death', 'children',
             'location contains', 'place of birth', 'place lived',
             'administrative division of country', 'country of administrative divisions',
             'company', 'neighborhood of', 'company founders', 'conjunction', 'feature of',
             'hyponym of', 'used for', 'part of', 'compare', 'evaluate for', 'component whole',
             'instrument agency', 'member collection', 'cause effect', 'entity destination',
             'content container', 'message topic', 'product producer', 'entity origin']
EET_SCHEMA = ['injure', 'born', 'marry', 'ransom', 'execute', 'Event trigger: phishing', 'sentence',
              'merge organization', 'charge indict', 'release parole', 'convict', 'data breach',
              'Event trigger: adverse event', 'sue', 'trial hearing', 'fine',
              'potential therapeutic event', 'transport', 'transfer money', 'attack',
              'patch vulnerability', 'phone write', 'acquit', 'end organization',
              'transfer ownership', 'meet', 'extradite', 'nominate', 'arrest jail', 'end position',
              'elect', 'die', 'demonstrate', 'pardon', 'divorce', 'Event trigger: declare bankruptcy',
              'discover vulnerability', 'start position', 'start organization', 'appeal']
EEA_SCHEMA = ['Treatment.Duration', 'agent', 'person', 'artifact', 'Subject.Race', 'defendant',
              'vulnerable system version', 'prosecutor', 'Subject.Disorder', 'Subject.Population',
              'price', 'victim', 'number of victim', 'adjudicator', 'vulnerable system owner',
              'organization', 'Treatment.Route', 'Treatment.Freq', 'target', 'Treatment.Disorder',
              'Subject.Gender', 'damage amount', 'patch', 'recipient', 'seller', 'trusted entity',
              'common vulnerabilities and exposures', 'beneficiary', 'instrument', 'origin',
              'attack pattern', 'Subject', 'supported platform', 'Subject.Age', 'number of data',
              'vulnerable system', 'vehicle', 'time', 'giver', 'discoverer', 'capabilities',
              'Effect', 'Treatment', 'Treatment.Dosage', 'plaintiff', 'tool', 'destination',
              'purpose', 'Treatment.Drug', 'releaser', 'compromised data', 'place',
              'payment method', 'buyer', 'Treatment.Time_elapsed', 'issues addressed', 'entity',
              'vulnerability', 'attacker', 'patch number', 'Combination.Drug']
